### ISSUE TITLE
g_regex_get_compile_flags is since GLib 2.26 but Geany builds with 2.20

### ISSUE THREAD

**Issue by scriptum** [geany/geany#340]
Cannot compile latest Geany from head for RHEL6. RHEL6 supports GLIB 2.22, in configure.ac I found version 2.20, but I get this error:

```
./src/search.c:1981: undefined reference to `g_regex_get_compile_flags'
```

https://developer.gnome.org/glib/stable/glib-Perl-compatible-regular-expressions.html#g-regex-get-compile-flags
This function is available only with GLib >= 2.26
